name: PlayerFreezer
main: me.mc_cloud.playerfreezer.Main
description: Admin tool that freezes players
version: 1.3.1
author: MC_Cloud
api-version: 1.18

commands:
  freeze:
  unfreeze:
  freezegun:
    aliases: [fg]
  
permissions:
  playerFreezer.use:
    default: op
    