name: PlayerFreezer
main: me.mc_cloud.playerfreezer.Main
description: Admin tool that freezes players
version: 2.2
author: MC_Cloud
api-version: 1.18

commands:
  freeze:
  unfreeze:
  freezegun:
    aliases: [fg]
  
permissions:
  playerFreezer.freeze:
    default: op
  playerFreezer.unfreeze:
    default: op
  playerFreezer.bypass:
    default: op
  playerFreezer.freeze-gun:
    default: op
    